server:
  port: ${PORT:8080}

spring:
  application:
    name: Channel0-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 60000
      max-lifetime: 1200000
      keepalive-time: 30000
      connection-timeout: 30000
      validation-timeout: 5000
      connection-test-query: SELECT 1
      initialization-fail-timeout: 0



  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          batch_versioned_data: true

logging:
  level:
    root: INFO
    com.example.channel0: DEBUG


admin:
  key: ${ADMIN_KEY}